config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  scope '(:locale)', locale: /en|cn/ do
	resources :articles, only: [:index, :show]
	resources :schools, only: [:index, :show] 
	# do 
	# 	resources :teachers, only: [:index]
	# end
	resources :abouts, only: [:index]
	resources :contacts, only: [:index]
	root to: "articles#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
  end
end

app/models/about.rb
class About < ApplicationRecord
	has_one_attached :photo1
	has_one_attached :photo2
	has_one_attached :photo3
	has_one_attached :photo4
	validates :title, :description, :title_cn, :description_cn, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
has_one_attached :photo1
has_one_attached :photo2
has_one_attached :photo3
has_one_attached :photo4
has_one_attached :photo5
has_one_attached :photo6
has_one_attached :photo7
has_one_attached :photo8

validates :title, :subtitle, :content, :title_cn, :subtitle_cn, :content_cn, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
	has_one_attached :photo1
	has_one_attached :photo2
	has_one_attached :photo3
	has_one_attached :photo4
	has_one_attached :photo5
	has_one_attached :photo6
	has_one_attached :photo7
	has_one_attached :photo8	
	has_many :teachers
	validates :title, :address, :content, :title_cn, :address_cn, :content_cn, presence: true
	geocoded_by :address_cn
  	after_validation :geocode, if: :will_save_change_to_address_cn?

  	rails_admin do
    	exclude_fields :longitude, :latitude
  	end
  end

app/models/teacher.rb
class Teacher < ApplicationRecord
	has_one_attached :photo
	# attr_accessor :remove_photo
	# after_save do
 #    	photo.purge if remove_photo == '1'
 #  	end
 #  	rails_admin do
 #    	field :name
 #    	field :description
 #    	field :name_cn
 #    	field :description_cn
 #    	field :photo, :active_storage do 
 #      		delete_method :delete_photo
 #      	end
 #    end


	belongs_to :school
	validates :name, :description, :name_cn, :description_cn, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable, :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	def index
		@about = About.first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_locale

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

  private

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale).to_sym
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :article_instance, only: [:show]
	def index
		@articles = Article.all 
	end

	def show
	end

	
	private

	def article_instance
		@article = Article.find(params[:id])
	end

	def article_attributes
		params.require(:article).permit(:title, :subtitle, :content, photos: [])
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index

	end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	
	def index
		@schools = School.where.not(latitude: nil, longitude: nil)
		arr = []
		@schools.geocoded.map do |school|
      		arr.push([school.latitude, school.longitude])
		end
		@markers = arr

	end

	def show
		@school = School.find(params[:id])
	end


end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/abouts/index.html.erb
<div class="container">
	<div class="about-card d-flex justify-content-around mt-3 pt-5 pl-5 pr-5 pb-5 mb-5">
		<div>
			<h1>
			<% if I18n.locale == I18n.default_locale %>
				<%= @about.title %>
			<% else %>
			 	<%= @about.title_cn %>
			<% end %>
			</h1>
			<p>
			<% if I18n.locale == I18n.default_locale %>
				<%= @about.description %>
			<% else %>
			 	<%= @about.description_cn %>
			<% end %>
			</p>
		</div>
		<% if @about.photo1.attached? %>
  			<%= cl_image_tag @about.photo1.key, height: 300, width: 400, crop: :fill %>
 		<% end %>
	</div>
	<div class="about-carousel-box">
		 <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
		  <ol class="carousel-indicators">
		    <% if @about.photo1.attached? %>
		        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
		    <% end %>
		    <% if @about.photo2.attached? %>
		      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
		    <% end %>
		    <% if @about.photo3.attached? %>
		      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
		    <% end %>
		    <% if @about.photo4.attached? %>
		      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
		    <% end %>
		   </ol>
		  <div class="carousel-inner">
		    <% if @about.photo1.attached? %>
		      <div class="carousel-item active">
		        <%= cl_image_tag @about.photo1.key, class:"d-block w-100 carousel-fix" %>
		      </div>
		    <% end %>
		    <% if @about.photo2.attached? %>
		      <div class="carousel-item">
		        <%= cl_image_tag @about.photo2.key, class:"d-block w-100 carousel-fix" %>
		      </div>
		    <% end %>
		    <% if @about.photo3.attached? %>
		      <div class="carousel-item">
		        <%= cl_image_tag @about.photo3.key, class:"d-block w-100 carousel-fix" %>
		      </div>
		    <% end %>
		    <% if @about.photo4.attached? %>
		      <div class="carousel-item">
		        <%= cl_image_tag @about.photo4.key, class:"d-block w-100 carousel-fix" %>
		      </div>
		    <% end %>
		  </div>

		  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div> 
	</div>
</div>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">



    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
    <div class="container-1">

      <div class="text-item">
        <h1 style="color: #01255B"><strong>Changing <span style="color: #E67E22"> lives </span>and<br>building<span< style="color: #E67E22"> opportunites </span></strong></h1>
        <p style="color: #00337E">Leading the way in ESL edcuation,<br>for more information contact us today.</p>
         <a class="btn btn-outline-warning" style="margin-top:30px" href="<%=contacts_path%>"><strong>Contact us</strong></a>
      </div>
        <div>
          <%=image_tag "index/teacher-lg.png" , class: "teacher" %>
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" class="wave" viewBox="0 0 4709 3168"><defs><style>.a{fill:#f0f8ff;}.b{fill:#fefefe;}</style></defs><path class="a" d="M2354.5,2107.06c-119.61,76.2-217.15,143.67-324.19,200C949.52,2875.59,0,2436.4,0,2436.4V3168H4709V1949.87S3537,1353.73,2354.5,2107.06Z"/><path class="b" d="M2354.5,2387.37c-119.61,56.07-217.15,105.72-324.19,147.15C949.52,2952.85,0,2629.7,0,2629.7V3168H4709V2271.72S3537,1833.09,2354.5,2387.37Z"/></svg>

    </div>

    </div>
      <div class="video-section">
          <%= video_tag "",
           autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>
      </div>

      <div class= flex-container-2>
        <div class="text-item-2">
        <h1 style="color: #01255B"><strong>With schools<br>throughout<span style="color: #E67E22"> Shanghai</span></strong></h1>
        <p style="color: #00337E">Find out more about our schools.</p>
        <a class="btn btn-outline-warning" style="margin-top:30px" href="<%=contacts_path%>"><strong>Find out more</strong></a>
      </div>
        <div>
          <%=image_tag "index/school.png" , class: "second_image" %>
        </div>
      </div>
    </div>
    <div class= flex-container-3>
      <div>
        <%=image_tag "index/news.png" , class: "third_image" %>
      </div>
      <div class="text-item-2">
        <h1 style="color: #01255B"><strong>Catch up on our<span style="color: #E67E22"> lastest <br> news</span> and events</strong></h1>
        <p style="color: #00337E">Read more on the lastest news<br>and information at Open English.</p>
        <a class="btn btn-outline-warning" style="margin-top:30px" href="<%=contacts_path%>"><strong>Find out more</a>
      </div>
    </div>
  </body>
</html>


<!--
<ol>
	<% @articles.each do |article| %>
		<li>
			<% if I18n.locale == I18n.default_locale %>
        		<h2><%= link_to article.title, article_path(article) %></h2>
        		<p><%= article.title%></p>
    		<% else %>
				<h2><%= link_to article.title_cn, article_path(article) %></h2>
				<p><%= article.title_cn%></p>
    		<% end%>
    		<% if article.photo1.attached? %>
  				<%= cl_image_tag article.photo1.key, height: 300, width: 400, crop: :fill %>
 			<% end %>

	<% end %>
</ol>

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Stitch_%28Lilo_%26_Stitch%29.svg/1200px-Stitch_%28Lilo_%26_Stitch%29.svg.png" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

app/views/articles/show.html.erb
<%= link_to "Back", root_path %>
<div class="article-box">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% if @article.photo1.attached? %>
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <% end %>
    <% if @article.photo2.attached? %>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <% end %>
    <% if @article.photo3.attached? %>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <% end %>
    <% if @article.photo4.attached? %>
      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <% end %>
    <% if @article.photo5.attached? %>
      <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    <% end %>
    <% if @article.photo6.attached? %>
      <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
    <% end %>
    <% if @article.photo7.attached? %>
      <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>
    <% end %>
    <% if @article.photo8.attached? %>
      <li data-target="#carouselExampleIndicators" data-slide-to="7"></li>
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% if @article.photo1.attached? %>
      <div class="carousel-item active">
        <%= cl_image_tag @article.photo1.key, class:"d-block w-100 carousel-fix" %>
      </div>
    <% end %>
    <% if @article.photo2.attached? %>
      <div class="carousel-item">
        <%= cl_image_tag @article.photo2.key, class:"d-block w-100 carousel-fix" %>
      </div>
    <% end %>
    <% if @article.photo3.attached? %>
      <div class="carousel-item">
        <%= cl_image_tag @article.photo3.key, class:"d-block w-100 carousel-fix" %>
      </div>
    <% end %>
    <% if @article.photo4.attached? %>
      <div class="carousel-item">
        <%= cl_image_tag @article.photo4.key, class:"d-block w-100 carousel-fix" %>
      </div>
    <% end %>
    <% if @article.photo5.attached? %>
      <div class="carousel-item">
        <%= cl_image_tag @article.photo5.key, class:"d-block w-100 carousel-fix" %>
      </div>
    <% end %>
    <% if @article.photo6.attached? %>
      <div class="carousel-item">
        <%= cl_image_tag @article.photo6.key, class:"d-block w-100 carousel-fix" %>
      </div>
    <% end %>
    <% if @article.photo7.attached? %>
      <div class="carousel-item">
        <%= cl_image_tag @article.photo7.key, class:"d-block w-100 carousel-fix" %>
      </div>
    <% end %>
    <% if @article.photo8.attached? %>
      <div class="carousel-item">
        <%= cl_image_tag @article.photo8.key, class:"d-block w-100 carousel-fix" %>
      </div>
    <% end %>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>  
    
  <div>
    <div style="color:grey" class="pt-3 pb-3">
      <%= @article.created_at.to_date %>
    </div>
    <div>
    <h3>
      <% if I18n.locale == I18n.default_locale %>
        <strong><%= @article.title %></strong>       
      <% else %>
        <strong><%= @article.title_cn %></strong>
      <% end %>
    </h3>
    </div>
     <h5>
      <% if I18n.locale == I18n.default_locale %>
        <%= @article.subtitle %> 
      <% else %>
        <%= @article.subtitle_cn %>
      <% end %>
    </h5>
    </div>
    <p>
      <% if I18n.locale == I18n.default_locale %>
          <%= @article.content %>
      <% else %>
     	    <%= @article.content_cn %>
      <%end %>
    </p>
  </div>
</div>

app/views/contacts/index.html.erb
<html>
  
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
</head>


<body>
<!-- d-flex justify-content-center
 -->

<div class="d-flex justify-content-center mt-5">

  <div class="blue-background contact-color contact-form pr-5 pl-5 pt-4">
    <h2  style="padding-bottom: 120px; font-size: 24px">Contact us</h2>
    <div class="d-flex justify-content-around "style="padding-top: 200px">
    <i class="fab fa-weixin icon-size" ></i>
    <a href="https://www.facebook.com/" target="_blank"> 
      <i class="fab fa-facebook-square contact-color icon-size"></i>
    </a>
    </div>
  </div>

  <div class="move-form bg-white pr-4 pt-4 pb-4 contact-form">
   <form id="fs-frm" name="simple-contact-form" accept-charset="utf-8" action="https://formspree.io/f/xpzolqld" method="post" >
    <fieldset id="fs-frm-inputs" >
      <div class="form-row ">
        <div class="form-group col-md-6">
          <label for="last-name" class="remove-bottom">Last Name</label>
          <input type="text" name="Last Name" class="form-control" id="last-name" placeholder="Last Name">
        </div>

        <div class="form-group col-md-6">
          <label for="first-name"  class="remove-bottom">First Name</label>
          <input type="text" name="First Name" class="form-control" id="first-name" placeholder="First Name">
        </div>
      </div>

      <div class="form-group ">
        <label for="email-address"  class="remove-bottom">Email Address</label>
        <input type="email" name="Email" class="form-control" id="email-address" placeholder="email@domain.tld" required="">
      </div>
      <div class="form-group">
        <label for="message" class="remove-bottom">Message</label>
        <textarea rows="5" name="Message" id="message" class="form-control" placeholder="I am interested to teach in OpenEnglish Studio" required=""></textarea>
      </div>

      <input type="hidden" name="_subject" id="email-subject" value="Contact Form Submission">
    </fieldset>

    <input style="float:right;" type="submit" value="Submit" class="btn btn-primary move-button-left mt-4">
  </form>
  </div>

</div>

<body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open English Studio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header class="header">
    <nav class="navbar navbar-expand-lg top py-3">
        <div class="container"><a href="<%=root_path %>"><%= image_tag "logos/open-logo.png", alt: "Le Wagon", width: 100, class: "logo"%></a>
            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler navbar-toggler-right"><i class="fa fa-bars"></i></button>

            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><h5 class="nav-link text-uppercase font-weight-bold"><%=link_to t('schools'),schools_path%></h5></li>
                    <li class="nav-item"><h5 class="nav-link text-uppercase font-weight-bold"><%=link_to t('news'), abouts_path%></h5></li>
                    <li class="nav-item"><h5 class="nav-link text-uppercase font-weight-bold"><%=link_to t('about'), abouts_path%></h5></li>
                    <li class="nav-item"><h5 class="nav-link text-uppercase font-weight-bold"><%=link_to t('contact'), contacts_path%></h5></li>
                    <li class="nav-item"><h5 class="nav-link text-uppercase font-weight-bold">
                      <% if I18n.locale == I18n.default_locale %>
                       <%= link_to "中文", { :locale=>'cn' } %>
                        <% else %>
                      <%= link_to "English", { :locale=>'en' } %>
                      <% end%>
                </ul>
            </div>
        </div>
    </nav>
</header>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= yield %>

  </body>
</html>



 <!--<% if user_signed_in? %>
                <%= button_to 'Exit', destroy_user_session_path, method: :delete %>
                <a class= "pr-3 pl-3" href="/admin">Admin Dashboard</a>
            <% else %>
                <div class="pr-3">
                <%= button_to 'Admin Login', new_user_session_path %>
                </div>
            <% end %>





    <!--<div class=" bg-black">
    <div class="d-flex justify-content-between align-items-center container pb-3">
        <a href="<%=root_path %>"><%= image_tag "logos/logo.png", alt: "Le Wagon", width: 100, class: "logo"%></a>
        <div class= "d-flex justify-content-between">

            <% if I18n.locale == I18n.default_locale %>
                <%= link_to "中文", { :locale=>'cn' } %>
            <% else %>
                <%= link_to "English", { :locale=>'en' } %>
            <% end%>
            <p class="pr-3 pl-3"><%=link_to t('school'), schools_path%></p>
            <p class="pr-3"><%=link_to t('about'), abouts_path%></p>
            <p class="pr-3"><%=link_to t("contact"), contacts_path%></p>
        </div>
    </div>
    </div>

<!<div class="navbar-wrapper">
<div class="container fluid">
<nav class="navbar navbar-expand-lg navbar-light bg-sticky-top fluid" style="background-opacity: 0;">
   <a class="navbar-brand" href="<%=root_path %>"><%= image_tag "logos/logo.png", width: 200 , class: "logo"%> </a>
  <button class="navbar-toggler" style="height: 60px" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <p class="nav-link" ><%=link_to t('Schools'), schools_path%></p>
      </li>
      <li class="nav-item active">
        <p class="nav-link"><%=link_to t('News'), schools_path%></p>
      </li>
      <li class="nav-item active">
       <p class="nav-link"><%=link_to t('About'), abouts_path%></p>
      </li>
      <li class="nav-item active">
        <p class="nav-link"><%=link_to t("Contact"), contacts_path%></p>
      </li>
      <li>
        <p class=nav-link>
          <% if I18n.locale == I18n.default_locale %>
            <%= link_to "中文", { :locale=>'cn' } %>
              <% else %>
            <%= link_to "English", { :locale=>'en' } %>
            <% end%>
        </p>
      </li>
    </ul>
  </div>
</nav>
</div>
</div>

app/views/schools/index.html.erb
<script src='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
<script>

setTimeout(() => {
	mapboxgl.accessToken = 'pk.eyJ1IjoiY2Fwb3dhbmciLCJhIjoiY2tjeTg2MnV2MDdjbTJ4cGtnaG9lb2p3cCJ9.9Lh3xU1oXA8qfpgOm1k86A';
		var map = new mapboxgl.Map({
		container: 'map',
		style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
		center: [121.473701, 31.230391], // starting position [lng, lat]
		zoom: 9 // starting zoom
		});

		var markers = JSON.parse(document.getElementById("map").dataset.markers);
		console.log(markers)
		markers.forEach((marker) => {
		 var marker = new mapboxgl.Marker()
		.setLngLat([marker[1], marker[0]])
		.addTo(map);
		})

    }, 100)
///eight: 160, width: 286, crop: :fill,
</script>

	<div class="container map-flex">
		
		<div class="school-cards pr-3">
			<% @schools.each do |school| %>
					<div class="card" style="width: 18rem;">
					  		<% if school.photo1.attached? %>
								<%= cl_image_tag school.photo1.key, height: 160, width: 286, crop: :fill %>
							<% end %>
					  <div class="card-body">
					  	<% if I18n.locale == I18n.default_locale %>
						    <h5 class="card-title"><%= link_to school.title, school_path(school)%></h5>
						    <p class="card-text"><%= school.address%></p>
					   	<% else %>
						    <h5 class="card-title"><%= link_to school.title_cn, school_path(school)%></h5>
						    <p class="card-text"><%= school.address_cn%></p>
						<% end %>
					  </div>
					</div>
			<% end %>
		</div>

		<div id='map' style='width: 400px; height: 560px;' data-markers="<%= @markers%>"></div>

	</div>

app/views/schools/show.html.erb
<%= link_to "Back", schools_path %>

<% if @school.photo1.attached? %>
  <%= cl_image_tag @school.photo1.key, height: 300, width: 400, crop: :fill %>
 <% end %>
 <% if @school.photo2.attached? %>
  <%= cl_image_tag @school.photo2.key, height: 300, width: 400, crop: :fill %>
 <% end %>
 <% if @school.photo3.attached? %>
  <%= cl_image_tag @school.photo3.key, height: 300, width: 400, crop: :fill %>
 <% end %>
 <% if @school.photo4.attached? %>
  <%= cl_image_tag @school.photo4.key, height: 300, width: 400, crop: :fill %>
 <% end %>
<% if @school.photo5.attached? %>
  <%= cl_image_tag @school.photo5.key, height: 300, width: 400, crop: :fill %>
 <% end %>
 <% if @school.photo6.attached? %>
  <%= cl_image_tag @school.photo6.key, height: 300, width: 400, crop: :fill %>
 <% end %>
 <% if @school.photo7.attached? %>
  <%= cl_image_tag @school.photo7.key, height: 300, width: 400, crop: :fill %>
 <% end %>
 <% if @school.photo8.attached? %>
  <%= cl_image_tag @school.photo8.key, height: 300, width: 400, crop: :fill %>
 <% end %>






<% if I18n.locale == I18n.default_locale %>
	<h1>
		<%= @school.title %>
		<%= @school.address %>
	</h1>
	<p>
		<%= @school.content %>
	</p>
	<% @school.teachers.each do |teacher| %>
		<li>
			<p><%= teacher.name%></p>
			<p><%= teacher.description%></p>
			<%= cl_image_tag teacher.photo.key, height: 300, width: 400, crop: :fill %>
		</li>
	<% end %>
<% else %>
 	<h1>
		<%= @school.title_cn %>
		<%= @school.address_cn %>
	</h1>
	<p>
		<%= @school.content_cn %>
	</p>
	<% @school.teachers.each do |teacher| %>
		<li>
			<p><%= teacher.name_cn%></p>
			<p><%= teacher.description_cn%></p>
		</li>
	<% end %>

<% end%>